Feature/update prisma schema
bloppaa/tickets-system pull request #1
Opened 2024-10-19 00:14 UTC by MaxStee1

2024-10-19 21:45 UTC, bloppaa requested changes
Arregla las líneas comentadas

2024-10-19 21:45 UTC, bloppaa commented on prisma/schema.prisma
> +  status      String   @default("open")
status debería ser de tipo `enum`. Ej:

```prisma
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  role  Role    @default(USER)
}

enum Role {
  USER
  ADMIN
}
```

2024-10-19 21:45 UTC, bloppaa commented on prisma/schema.prisma
> +  personRut   String
la referencia debería ser el `id` de la persona y no su `rut`. La razón es porque buscar un string es mucho mas ineficiente que buscar un número, y por ende, ralentizará la base de datos.

2024-10-19 21:45 UTC, bloppaa commented on prisma/seed.js
> +      where: { rut: person.rut }, // search by RUT
Actualizar respecto a lo mencionado previamente

2024-10-20 21:57 UTC, MaxStee1 commented on prisma/seed.js
> +      where: { rut: person.rut }, // search by RUT
eso es para verificar si la persona esta o no en la base de datos, y como en el datatest no se asigna un id (es autoincrement), se busca por alguna clave unica, puede ser email, o el rut

2024-10-23 02:38 UTC, bloppaa approved these changes

2024-10-23 03:05 UTC, merged